[project]
name = "fastapi-chile-time"
version = "0.1.0"
description = "API en FastAPI que entrega hora UTC y hora oficial de Chile usando NTP."
authors = [
    { name = "Maximiliano", email = "mhurtadop@correo.uss.cl" }
]
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "fastapi",
    "uvicorn",
    "ntplib",
    "tzdata",
    "pytest",
    "httpx",
]


[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["."]



